### ISSUE TITLE
Emails stop sending

### ISSUE THREAD

**Issue by lepenr** [MAPESO/nextjs-sendgrid#3]
Hi Markozxuu,

fyi I have used your code for sending emails, was working till few weeks ago,  not it stopped sending emails.

Cheers,
Robert

**Comment by markozxuu** [comment]
Hi 👋 ! you could detail your problem better. The code that I exposed in my article dev.to I am using it in a project and it works well : )

**Comment by lepenr** [comment]
Sorry, being not specific, I just could not figure out why it stopped working. 
Was using your tut and it worker, but it stopped now. 
Also seems like your test web stopped sending it: https://next-sendgrid.now.sh/

**Comment by lepenr** [comment]
Sorry, was missing domain aut. 
Thanks for your tut anyway! It helped a lot.
